// <auto-generated />
using System;
using Flashcards.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flashcards.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629093518_AddEntityRelationships")]
    partial class AddEntityRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flashcards.Api.Models.CandidateWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageAnalysisId")
                        .HasColumnType("integer");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PageAnalysisId");

                    b.ToTable("CandidateWords");
                });

            modelBuilder.Entity("Flashcards.Api.Models.PageAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageScanId")
                        .HasColumnType("integer");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PageScanId")
                        .IsUnique();

                    b.ToTable("PageAnalyses");
                });

            modelBuilder.Entity("Flashcards.Api.Models.PageScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PageScans");
                });

            modelBuilder.Entity("Flashcards.Api.Models.WordCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WordCards");
                });

            modelBuilder.Entity("Flashcards.Api.Models.CandidateWord", b =>
                {
                    b.HasOne("Flashcards.Api.Models.PageAnalysis", "PageAnalysis")
                        .WithMany("CandidateWords")
                        .HasForeignKey("PageAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageAnalysis");
                });

            modelBuilder.Entity("Flashcards.Api.Models.PageAnalysis", b =>
                {
                    b.HasOne("Flashcards.Api.Models.PageScan", "PageScan")
                        .WithOne("PageAnalysis")
                        .HasForeignKey("Flashcards.Api.Models.PageAnalysis", "PageScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageScan");
                });

            modelBuilder.Entity("Flashcards.Api.Models.PageAnalysis", b =>
                {
                    b.Navigation("CandidateWords");
                });

            modelBuilder.Entity("Flashcards.Api.Models.PageScan", b =>
                {
                    b.Navigation("PageAnalysis");
                });
#pragma warning restore 612, 618
        }
    }
}
